# Generated by Django 6.0.3 on 2026-04-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL if no file uploaded', null=True),
        ),
    ]
