# Generated by Django 6.0.3 on 2026-04-11 17:59

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_images_to_gallery(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductImage = apps.get_model('products', 'ProductImage')
    for p in Product.objects.all():
        if ProductImage.objects.filter(product_id=p.pk).exists():
            continue
        if p.image:
            ProductImage.objects.create(product_id=p.pk, image=p.image, sort_order=0)
        elif p.image_url:
            ProductImage.objects.create(product_id=p.pk, image_url=p.image_url, sort_order=0)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like new'), ('good', 'Good'), ('fair', 'Fair'), ('used', 'Used')], default='new', help_text='Condition / quality label for buyers', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Legacy single upload; prefer ProductImage gallery (max 5).', null=True, upload_to='products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Legacy external URL; prefer ProductImage gallery.', null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/gallery/%Y/%m/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(copy_legacy_images_to_gallery, noop_reverse),
    ]
