# Generated by Django 6.0.3 on 2026-05-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productinteraction_searchhistory_userinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(blank=True, max_length=80)),
                ('cta_text', models.CharField(default='Shop now', help_text='Button label, e.g. "Shop now", "View offers"', max_length=20)),
                ('bg_color', models.CharField(default='#F97316', help_text='Hex color for background, e.g. #F97316 (orange)', max_length=7)),
                ('icon_name', models.CharField(default='shopping_bag_outlined', help_text='Flutter Icons name', max_length=40)),
                ('image', models.ImageField(blank=True, help_text='Optional banner image (overrides icon_name when set)', null=True, upload_to='banners/')),
                ('action_type', models.CharField(choices=[('category', 'Navigate to Category'), ('product', 'Navigate to Product'), ('url', 'Open External URL'), ('none', 'No Action')], default='none', max_length=10)),
                ('action_value', models.CharField(blank=True, help_text='Category ID, Product ID, or URL depending on action_type', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = shown first')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
