# Generated by Django 6.0.3 on 2026-08-28 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_seed_default_banners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, help_text='Partner-supplied SKU/ID for idempotent partner-API sync (unique per seller).', max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('seller', 'external_id'), name='uniq_product_seller_external_id'),
        ),
    ]
