# Generated by Django 6.0.3 on 2026-08-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_age_restricted',
            field=models.BooleanField(default=False, help_text='Buyers under 18 (or with no date of birth on file) never see or can buy products in this category.'),
        ),
    ]
