# Generated by Django 6.0.3 on 2026-04-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seller_nrc_and_delivery_license_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
