# Generated by Django 6.0.3 on 2026-04-11 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mtn_momo', 'MTN MoMo'), ('airtel_money', 'Airtel Money'), ('zamtel', 'Zamtel Kwacha')], max_length=20)),
                ('account_phone', models.CharField(help_text='Wallet / mobile money number', max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider', 'account_phone'), name='uniq_buyer_payment_user_provider_phone')],
            },
        ),
    ]
