# Generated by Django 6.0.3 on 2026-06-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_deliveryprofile_vehicle_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('delivery', 'Delivery'), ('admin', 'Admin'), ('staff', 'Staff')], default='buyer', max_length=10),
        ),
    ]
