# Generated by Django 6.0.3 on 2026-08-28 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g. "Staging" or "ERP production sync" — lets a seller with multiple keys tell them apart.', max_length=100)),
                ('prefix', models.CharField(editable=False, max_length=12)),
                ('hashed_key', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_api_keys', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller API key',
                'verbose_name_plural': 'Seller API keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
