# Generated by Django 6.0.3 on 2026-08-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_gender_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
    ]
