# Generated by Django 6.0.3 on 2026-09-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_sellerprofile_shop_logo_shop_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short stable identifier, e.g. ZM, RW, ZW — what a foreign key actually stores.', max_length=2, unique=True)),
                ('name', models.CharField(help_text='e.g. Zambia, Rwanda, Zimbabwe', max_length=100)),
                ('currency_code', models.CharField(help_text='e.g. ZMW, RWF, USD', max_length=3)),
                ('calling_code', models.CharField(help_text='e.g. 260, 250, 263 — no leading +', max_length=5)),
                ('is_active', models.BooleanField(default=False, help_text="A country can exist (be configured) before it's opened to buyers/sellers.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
