# Generated by Django 6.0.3 on 2026-10-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_sellerprofile_shop_logo_shop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_alcohol_products',
            field=models.BooleanField(default=True, help_text='Whether an 18+ buyer wants alcohol-category products in their listings. Has no effect on under-18 or no-date-of-birth buyers, who never see them regardless (see is_adult / products.models.exclude_restricted_for_user).'),
        ),
    ]
