# Generated by Django 6.0.3 on 2026-09-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_seed_zambia_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sellers', to='accounts.country'),
        ),
    ]
