# Generated by Django 6.0.3 on 2026-04-11 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_buyer_payment_method'),
        ('orders', '0002_phase1_delivery_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_account_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.buyerpaymentmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
