# Generated by Django 6.0.3 on 2026-06-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cancellation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time_slot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='quoted_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quoted_eta_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
