# Generated by Django 6.0.3 on 2026-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_pickup_and_distance_fields_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Buyer service fee, snapshotted from PlatformSettings.buyer_service_fee_rate at order creation time.', max_digits=10),
        ),
    ]
