# Generated by Django 6.0.3 on 2026-10-05 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_service_fee'),
        ('products', '0011_category_is_age_restricted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_address', models.TextField()),
                ('delivery_lat', models.FloatField(blank=True, null=True)),
                ('delivery_lng', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(help_text='Straight-line distance from the seller’s shop at request time.')),
                ('status', models.CharField(choices=[('pending', 'Waiting for seller'), ('proposed', 'Seller proposed'), ('accepted', 'Buyer accepted'), ('declined', 'Seller declined'), ('expired', 'Expired — seller never responded')], default='pending', max_length=10)),
                ('proposed_method', models.CharField(blank=True, default='', max_length=200)),
                ('proposed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('decline_reason', models.CharField(blank=True, default='', max_length=300)),
                ('expires_at', models.DateTimeField(help_text='Seller must respond by this time, or the request auto-expires.')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the seller proposed or declined.', null=True)),
                ('decided_at', models.DateTimeField(blank=True, help_text='When the buyer accepted (or it expired).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_request', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'proposed'])), fields=('buyer', 'product'), name='one_live_transport_request_per_buyer_product')],
            },
        ),
    ]
