# Generated by Django 6.0.3 on 2026-10-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_transport_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Buyer service fee, snapshotted at order creation time from portal.models.get_buyer_service_fee_rate (a tiered rate by order subtotal, or the flat PlatformSettings.buyer_service_fee_rate if no tiers are configured).', max_digits=10),
        ),
    ]
