# Generated by Django 6.0.3 on 2026-04-21 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_alter_cartitem_unique_together_cartitem_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit (Buyer paying)'), ('payout', 'Payout(Paying Seller/Delivery)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('provider', models.CharField(help_text='e.g MTN_MOMO_ZMW, AIRTEL_MOMO_ZMW, ZAMTEL_MOMO_ZMW', max_length=50)),
                ('payer_number', models.CharField(help_text='Phone number of the transaction', max_length=15)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted by PawaPay'), ('completed', 'Completed/Successful'), ('failed', 'Failed'), ('duplicate_ignored', 'Duplicate Ignored')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
