# Generated by Django 6.0.3 on 2026-04-25 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payout_stage',
            field=models.CharField(choices=[('na', 'Not Applicable'), ('pickup_pending_scan', 'Waiting Pickup QR Scan'), ('dropoff_pending_scan', 'Waiting Dropoff QR Scan'), ('ready_for_payout', 'Ready For Payout'), ('payout_sent', 'Payout Sent'), ('payout_paid', 'Payout Paid'), ('payout_failed', 'Payout Failed')], default='na', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_role',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('delivery', 'Delivery'), ('platform', 'Platform')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trigger_event',
            field=models.CharField(choices=[('manual', 'Manual'), ('pickup_qr', 'Pickup QR'), ('dropoff_qr', 'Dropoff QR'), ('order_cancelled', 'Order Cancelled')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer_number',
            field=models.CharField(help_text='Phone number for deposit/payout/refund', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(help_text='e.g MTN_MOMO_ZMB, AIRTEL_OAPI_ZMB, ZAMTEL_MONEY_ZMB', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit (Buyer paying)'), ('payout', 'Payout (Paying Seller/Delivery)'), ('refund', 'Refund (Returning buyer funds)')], max_length=10),
        ),
    ]
