# Generated by Django 6.0.3 on 2026-05-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_payout_stage_transaction_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payout_method',
            field=models.CharField(choices=[('manual', 'Manual (platform sends from own phone)'), ('gateway', 'Gateway (PawaPay payout API)')], default='manual', max_length=10),
        ),
    ]
