# Generated by Django 6.0.3 on 2026-07-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_proof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trigger_event',
            field=models.CharField(choices=[('manual', 'Manual'), ('pickup_qr', 'Pickup QR'), ('dropoff_qr', 'Dropoff QR'), ('order_cancelled', 'Order Cancelled'), ('refund_request', 'Refund Request Approved')], default='manual', max_length=20),
        ),
    ]
