# Generated by Django 6.0.3 on 2026-09-24 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_transaction_trigger_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('pawapay', 'PawaPay (mobile money)'), ('lenco', 'Lenco (card / bank)')], default='pawapay', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Processing fee the provider reported, when it reports one.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_reference',
            field=models.CharField(blank=True, default='', help_text="The provider's own reference for this transaction (e.g. Lenco's lencoReference).", max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile money'), ('card', 'Card'), ('bank', 'Bank account')], default='mobile_money', max_length=15),
        ),
        migrations.CreateModel(
            name='PayoutBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=34)),
                ('account_name', models.CharField(max_length=150)),
                ('country', models.CharField(default='zm', max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Destination account for a bank payout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.payoutbankaccount'),
        ),
        migrations.AddConstraint(
            model_name='payoutbankaccount',
            constraint=models.UniqueConstraint(fields=('user', 'bank_id', 'account_number'), name='unique_payout_bank_account_per_user'),
        ),
    ]
