# Generated by Django 6.0.3 on 2026-09-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_lenco_gateway_fields_and_bank_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutbankaccount',
            name='name_matches',
            field=models.BooleanField(default=False, help_text="The bank's account holder name matches the owner's registered name. Accounts that don't match are never paid automatically — staff review first."),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_at',
            field=models.DateTimeField(blank=True, help_text='When a refund was promised to the buyer by (card refunds).', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_deducted',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee taken out of a payout before it is sent (e.g. the bank transfer fee). `amount` is what the recipient receives; amount + fee_deducted is what left their earnings.', max_digits=10),
        ),
    ]
