# Generated by Django 6.0.3 on 2026-10-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_transaction_fee_deducted_due_at_and_bank_name_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('pawapay', 'PawaPay (mobile money)'), ('lenco', 'Lenco (card / bank)'), ('lipila', 'Lipila (card)')], default='pawapay', max_length=10),
        ),
    ]
