# Generated by Django 6.0.3 on 2026-04-07 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('area', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base delivery rate in ZMW', max_digits=6)),
                ('per_km_rate', models.DecimalField(decimal_places=2, help_text='Rate per km in ZMW', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('pickup_location', models.JSONField(default=dict)),
                ('delivery_location', models.JSONField(default=dict)),
                ('current_location', models.JSONField(default=dict)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_distance', models.FloatField(help_text='Distance in km')),
                ('estimated_duration', models.IntegerField(help_text='Duration in minutes')),
                ('actual_distance', models.FloatField(blank=True, null=True)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('delivery_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='delivery.deliveryassignment')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['delivery_assignment', 'timestamp'], name='delivery_de_deliver_3ded26_idx')],
            },
        ),
    ]
