# Generated by Django 6.0.3 on 2026-04-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryhandofftoken_deliveryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='final_eta_error_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='initial_estimated_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='last_eta_recomputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='reroute_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='route_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='route_source',
            field=models.CharField(default='haversine_fallback', max_length=32),
        ),
    ]
