# Generated by Django 6.0.3 on 2026-04-14 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliveryassignment_final_eta_error_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTelemetrySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='accepted', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_s', models.PositiveIntegerField()),
                ('distance_m', models.FloatField()),
                ('derived_speed_kmh', models.FloatField(blank=True, null=True)),
                ('reported_speed_kmh', models.FloatField(blank=True, null=True)),
                ('route_source', models.CharField(blank=True, default='', max_length=32)),
                ('route_confidence', models.FloatField(blank=True, null=True)),
                ('route_distance_m', models.FloatField(blank=True, null=True)),
                ('route_duration_s', models.FloatField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Mon, 6=Sun')),
                ('hour_of_day', models.PositiveSmallIntegerField(help_text='0..23')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_segments', to='delivery.deliveryassignment')),
                ('from_tracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_from_segments', to='delivery.deliverytracking')),
                ('to_tracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_to_segments', to='delivery.deliverytracking')),
            ],
            options={
                'ordering': ['-ended_at'],
                'indexes': [models.Index(fields=['delivery_assignment', 'ended_at'], name='delivery_de_deliver_93eb67_idx'), models.Index(fields=['phase', 'weekday', 'hour_of_day'], name='delivery_de_phase_b777e9_idx')],
            },
        ),
    ]
