# Generated by Django 6.0.3 on 2026-04-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliverytelemetrysegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySpeedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='in_transit', max_length=20)),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Mon, 6=Sun')),
                ('hour_of_day', models.PositiveSmallIntegerField(help_text='0..23')),
                ('samples', models.PositiveIntegerField(default=0)),
                ('total_distance_m', models.FloatField(default=0)),
                ('total_duration_s', models.FloatField(default=0)),
                ('avg_speed_kmh', models.FloatField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['phase', 'weekday', 'hour_of_day'],
                'constraints': [models.UniqueConstraint(fields=('phase', 'weekday', 'hour_of_day'), name='uniq_speed_profile_phase_weekday_hour')],
            },
        ),
    ]
