# Generated by Django 6.0.3 on 2026-04-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliveryspeedprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Charge per kilometre for long-distance trips (ZMW)', max_digits=6)),
                ('short_distance_threshold_km', models.FloatField(default=3.0, help_text='Trips at or below this distance (km) get the flat rate')),
                ('short_distance_flat_rate', models.DecimalField(decimal_places=2, default=30.0, help_text='Flat delivery fee for short-distance trips (ZMW)', max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Pricing Config',
                'verbose_name_plural': 'Delivery Pricing Config',
            },
        ),
    ]
