# Generated by Django 6.0.3 on 2026-04-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_delivery_pricing_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytracking',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
