# Generated by Django 6.0.3 on 2026-09-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_sellerprofile_country'),
        ('delivery', '0009_alter_deliverytracking_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypricingconfig',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_pricing_configs', to='accounts.country'),
        ),
    ]
