# Generated by Django 6.0.3 on 2026-10-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_deliverytracking_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypricingconfig',
            name='max_delivery_distance_km',
            field=models.FloatField(default=100.0, help_text='Trips beyond this distance are not offered as normal rider delivery — a per-km fee at that range would far exceed most products’ value, and no rider is realistically making the trip. Buyers beyond this range see Pickup and the option to request the seller arrange transport instead.'),
        ),
    ]
