# Generated by Django 6.0.3 on 2026-05-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_payment_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'New Order Placed'), ('order_accepted', 'Order Accepted'), ('order_preparing', 'Order Being Prepared'), ('order_ready', 'Order Ready for Pickup'), ('order_out_for_delivery', 'Order Out for Delivery'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('payout_completed', 'Payout Completed'), ('delivery_assigned', 'Delivery Assigned'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('general', 'General')], default='general', max_length=32),
        ),
    ]
