# Generated by Django 6.0.3 on 2026-06-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'New Order Placed'), ('order_accepted', 'Order Accepted'), ('order_preparing', 'Order Being Prepared'), ('order_ready', 'Order Ready for Pickup'), ('order_out_for_delivery', 'Order Out for Delivery'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('payout_completed', 'Payout Completed'), ('delivery_assigned', 'Delivery Assigned'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('welcome', 'Welcome'), ('announcement', 'Announcement'), ('general', 'General')], default='general', max_length=32),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('buyers', 'Buyers Only'), ('sellers', 'Sellers Only'), ('delivery', 'Delivery Agents Only')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
