"""
Django settings for pocket_backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Load .env file if present (development convenience — no-op in production)
load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENVIRONMENT = os.environ.get('DJANGO_ENV', 'development')

# --- Maps / routing (Phase 2+) ---
OSRM_BASE_URL = os.environ.get(
    'OSRM_BASE_URL', 'https://router.project-osrm.org'
).rstrip('/')
NOMINATIM_USER_AGENT = os.environ.get(
    'NOMINATIM_USER_AGENT',
    'PocketShop/1.0 (https://example.com/contact)',
)
GEOCODING_CACHE_TTL = int(os.environ.get('GEOCODING_CACHE_TTL', '86400'))
ROUTING_CACHE_TTL = int(os.environ.get('ROUTING_CACHE_TTL', '3600'))
ROUTING_PROVIDER_ORDER = [
    p.strip() for p in os.environ.get('ROUTING_PROVIDER_ORDER', 'osrm').split(',')
    if p.strip()
]
ROUTING_CONFIDENCE_THRESHOLD = float(
    os.environ.get('ROUTING_CONFIDENCE_THRESHOLD', '0.55')
)
ROUTING_FALLBACK_SPEED_KMH = float(
    os.environ.get('ROUTING_FALLBACK_SPEED_KMH', '22')
)
DELIVERY_AVG_SPEED_KMH = float(os.environ.get('DELIVERY_AVG_SPEED_KMH', '22'))
DELIVERY_MAX_AVG_SPEED_KMH = float(
    os.environ.get('DELIVERY_MAX_AVG_SPEED_KMH', '38')
)
DELIVERY_TRAFFIC_MULTIPLIER = float(
    os.environ.get('DELIVERY_TRAFFIC_MULTIPLIER', '1.20')
)
DELIVERY_MIN_ETA_MINUTES = int(
    os.environ.get('DELIVERY_MIN_ETA_MINUTES', '4')
)
DELIVERY_SPEED_PROFILE_MIN_SAMPLES = int(
    os.environ.get('DELIVERY_SPEED_PROFILE_MIN_SAMPLES', '6')
)
DELIVERY_SPEED_PROFILE_DAYTYPE_MIN_SAMPLES = int(
    os.environ.get('DELIVERY_SPEED_PROFILE_DAYTYPE_MIN_SAMPLES', '10')
)
DELIVERY_SPEED_SMOOTHING_ALPHA = float(
    os.environ.get('DELIVERY_SPEED_SMOOTHING_ALPHA', '0.35')
)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'pocket-delivery',
    }
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

_secret = os.environ.get('DJANGO_SECRET_KEY', '')
if not _secret:
    if ENVIRONMENT == 'development':
        _secret = 'django-insecure-dev-only-key-do-not-use-in-production'
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY environment variable must be set in production.'
        )
SECRET_KEY = _secret

DEBUG = ENVIRONMENT == 'development'

# Local + ngrok: set PUBLIC_BACKEND_URL=https://YOUR.ngrok-free.app when your tunnel changes.
# AWS later: set DJANGO_ALLOWED_HOSTS, DJANGO_CSRF_TRUSTED_ORIGINS, PUBLIC_BACKEND_URL in the console.
PUBLIC_BACKEND_URL = os.environ.get('PUBLIC_BACKEND_URL', '').rstrip('/')

_allowed = os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()
_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '').strip()

ALLOWED_HOSTS = (
    [h.strip() for h in _allowed.split(',') if h.strip()]
    if _allowed
    else (['*'] if DEBUG else ['localhost', '127.0.0.1'])
)
if _railway_domain and _railway_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_domain)

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

_csrf = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').strip()
CSRF_TRUSTED_ORIGINS = [o.strip().rstrip('/') for o in _csrf.split(',') if o.strip()]
if PUBLIC_BACKEND_URL and PUBLIC_BACKEND_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.insert(0, PUBLIC_BACKEND_URL)
if _railway_domain:
    _railway_origin = f'https://{_railway_domain}'
    if _railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_railway_origin)
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000']

# DRF Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'accounts.error_logging.api_exception_handler',
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/minute',
        'qr_verify': '10/minute',
    },
}

# JWT Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'


# Application definition

JAZZMIN_SETTINGS = {
    'site_title': 'Pocket Admin',
    'site_header': 'Pocket',
    'site_brand': 'Pocket',
    'site_logo': 'admin/img/pocket_logo.jpg',
    'site_logo_classes': 'img-circle elevation-3',
    'login_logo': 'admin/img/pocket_logo.jpg',
    'login_logo_dark': 'admin/img/pocket_logo.jpg',
    'site_icon': 'admin/img/pocket_logo.jpg',
    'welcome_sign': 'Welcome to Pocket Admin',
    'copyright': 'Pocket Shop',
    'search_model': ['accounts.User'],
    'topmenu_links': [
        {'name': 'Dashboard', 'url': 'admin:index', 'permissions': ['auth.view_user']},
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'hide_apps': [],
    'icons': {
        'accounts.user': 'fas fa-users',
        'accounts.verificationrequest': 'fas fa-id-card',
        'orders.order': 'fas fa-shopping-bag',
        'payments.transaction': 'fas fa-money-bill-wave',
        'portal.platformsettings': 'fas fa-cogs',
        'delivery.deliverypricingconfig': 'fas fa-truck',
        'delivery.deliveryzone': 'fas fa-map-marked-alt',
        'notifications.notification': 'fas fa-bell',
        'products.product': 'fas fa-box',
    },
    'default_icon_parents': 'fas fa-folder',
    'default_icon_children': 'fas fa-circle',
    'related_modal_active': True,
    'show_ui_builder': False,
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-cyan',
    'accent': 'accent-teal',
    'navbar': 'navbar-cyan navbar-dark',
    'no_navbar_border': True,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-teal',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': False,
    'theme': 'default',
    'dark_mode_theme': None,
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'accounts',
    'products',
    'orders',
    'delivery',
    'reviews',
    'payments',
    'portal',
    'notifications',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pocket_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pocket_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    DATABASES = {'default': dj_database_url.parse(_database_url, conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'pocket_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media storage: DigitalOcean Spaces (S3-compatible) when AWS keys are set,
# Cloudinary as fallback, local filesystem otherwise.
_spaces_key = os.environ.get('AWS_ACCESS_KEY_ID', '')
_cloudinary_url = os.environ.get('CLOUDINARY_URL', '')

if _spaces_key:
    INSTALLED_APPS += ['storages']
    AWS_ACCESS_KEY_ID = _spaces_key
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'pocketbucket1')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', 'https://lon1.digitaloceanspaces.com')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'lon1')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', 'pocketbucket1.lon1.digitaloceanspaces.com')
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_DEFAULT_ACL = None          # bucket is set to public in DO dashboard
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    STORAGES = {
        'default': {'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }
elif _cloudinary_url:
    INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']
    STORAGES = {
        'default': {'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }
    CLOUDINARY_STORAGE = {'CLOUDINARY_URL': _cloudinary_url}
    MEDIA_URL = '/media/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# PAWAPAY CONFIGURATION (set PAWAPAY_JWT_TOKEN in AWS / local env for production)
PAWAPAY_JWT_TOKEN = os.environ.get('PAWAPAY_JWT_TOKEN', '').strip()
PAWAPAY_BASE_URL = os.environ.get('PAWAPAY_BASE_URL', 'https://api.pawapay.io/v2')

# Webhook signature verification — set this from PawaPay dashboard.
# In DEBUG mode the webhook handler will skip verification if this is empty.
PAWAPAY_WEBHOOK_SECRET = os.environ.get('PAWAPAY_WEBHOOK_SECRET', '')

# Platform commission taken from each order (0.05 = 5%).
PLATFORM_COMMISSION_RATE = float(os.environ.get('PLATFORM_COMMISSION_RATE', '0.05'))

# Maximum minutes a paid order can sit in 'accepted' before auto-cancel + refund.
ORDER_ACCEPTANCE_TIMEOUT_MINUTES = int(
    os.environ.get('ORDER_ACCEPTANCE_TIMEOUT_MINUTES', '30')
)

# AFRICA'S TALKING CONFIGURATION
AFRICAS_TALKING_USERNAME = os.environ.get('AFRICAS_TALKING_USERNAME', 'sandbox')
AFRICAS_TALKING_API_KEY = os.environ.get('AFRICAS_TALKING_API_KEY', '')
AFRICAS_TALKING_SENDER_ID = os.environ.get('AFRICAS_TALKING_SENDER_ID', 'POCKETSHOP')

# FIREBASE: set FIREBASE_CREDENTIALS_JSON to the full service-account JSON string in production.
# Leave empty in dev — push notifications are silently skipped when not configured.
FIREBASE_CREDENTIALS_JSON = os.environ.get('FIREBASE_CREDENTIALS_JSON', '')

# PAYOUT_METHOD: 'manual' = admin pays from their own phone, 'gateway' = PawaPay payout API.
# Switch to 'gateway' in env when PawaPay grants payout access — no code change needed.
PAYOUT_METHOD = os.environ.get('PAYOUT_METHOD', 'manual')
