# Generated by Django 6.0.3 on 2026-06-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.05, help_text='Platform commission taken from each order. 0.05 = 5%, 0.10 = 10%.', max_digits=5)),
                ('order_acceptance_timeout_minutes', models.PositiveIntegerField(default=30, help_text='Minutes a paid order can sit in accepted status before auto-cancel.')),
                ('delivery_per_km_rate', models.DecimalField(decimal_places=2, default=8.0, help_text='ZMW charged per km for long-distance deliveries.', max_digits=8)),
                ('delivery_short_distance_threshold_km', models.DecimalField(decimal_places=2, default=2.0, help_text='Distances at or below this get the flat rate instead.', max_digits=5)),
                ('delivery_short_distance_flat_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='ZMW flat rate charged for short deliveries.', max_digits=8)),
                ('payout_method', models.CharField(choices=[('manual', 'Manual (admin sends from phone)'), ('gateway', 'Gateway (PawaPay automated)')], default='manual', help_text='How seller and rider payouts are processed after delivery.', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When True, API returns 503 for all non-admin requests.')),
                ('maintenance_message', models.TextField(blank=True, default='We are performing maintenance. Please try again shortly.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
