# Generated by Django 6.0.3 on 2026-06-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='delivery_per_km_rate',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='delivery_short_distance_flat_rate',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='delivery_short_distance_threshold_km',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='buyer_service_fee_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Service fee added to buyer order total. 0.02 = 2%, 0 = no fee.', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='payout_fee_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Fee charged when paying out to sellers or riders. 0.01 = 1%, 0 = no fee.', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='rider_commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Commission deducted from rider delivery earnings. 0.10 = 10%, 0 = no cut.', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='seller_commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.05, help_text='Commission deducted from seller earnings per order. 0.05 = 5%.', max_digits=5),
        ),
    ]
