# Generated by Django 6.0.3 on 2026-06-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_restructure_platform_settings_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='GMV (order totals)')),
                ('delivery_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('seller_commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rider_commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('buyer_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revenue Snapshot',
                'verbose_name_plural': 'Revenue Snapshots',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
