# Generated by Django 6.0.3 on 2026-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_add_revenue_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='bank_payout_fee',
            field=models.DecimalField(decimal_places=2, default=50, help_text="Lenco's flat fee per bank transfer (ZMW). Deducted from the seller's payout.", max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='bank_payout_min_amount',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Smallest earnings withdrawal (ZMW) a seller can send to a bank account.', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='bank_payouts_enabled',
            field=models.BooleanField(default=False, help_text='Let sellers withdraw to a bank account. Riders always use mobile money.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='card_payments_enabled',
            field=models.BooleanField(default=False, help_text='Let buyers pay by card at checkout. Also needs the Lenco keys set on the server.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='card_refund_business_days',
            field=models.PositiveIntegerField(default=5, help_text='Business days promised to buyers for a card refund (shown on their order).'),
        ),
    ]
