# Generated by Django 6.0.3 on 2026-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_lenco_card_and_bank_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='card_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text="Lenco's fixed card fee per payment (ZMW). Only used to show buyers an estimate.", max_digits=6),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='card_fee_percent',
            field=models.DecimalField(decimal_places=2, default=3.8, help_text="Lenco's card fee, as a percentage. Only used to show buyers an estimate at checkout.", max_digits=5),
        ),
    ]
