# Generated by Django 6.0.3 on 2026-10-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_card_fee_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerServiceFeeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_value', models.DecimalField(decimal_places=2, help_text='Inclusive lower bound of the order subtotal (ZMW) this tier applies to.', max_digits=10)),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive upper bound (ZMW). Leave blank for "and above" (no upper limit).', max_digits=10, null=True)),
                ('fee_rate', models.DecimalField(decimal_places=4, help_text='Service fee charged to buyers for orders in this range. 0.05 = 5%.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Buyer service fee tier',
                'ordering': ['min_order_value'],
            },
        ),
    ]
